import { Link } from "expo-router";
import { ActivityIndicator, FlatList, Pressable, RefreshControl, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";

import { Notice, PrimaryButton } from "@/components/form-controls";
import { useCursorList } from "@/services/api/paginated";
import { colors, radii, spacing } from "@/theme/tokens";

type Chat = { id: string; unreadCount: number; otherUser: { name: string | null } | null; lastMessage: { text: string | null; imageUrl: string | null; createdAt: string } | null };

export default function InboxScreen() {
  const { query, items, loadMore } = useCursorList<Chat>({ queryKey: ["chats"], path: "/chats" });
  return <SafeAreaView style={styles.safe} edges={["top"]}><View style={styles.header}><Text style={styles.title}>Inbox</Text><Text style={styles.detail}>Messages with owners and renters.</Text></View>{query.isPending ? <ActivityIndicator style={styles.loader} color={colors.primary} size="large" /> : query.isError ? <View style={styles.state}><Notice>Conversations could not be loaded.</Notice><PrimaryButton title="Try again" onPress={() => void query.refetch()} /></View> : <FlatList data={items} keyExtractor={(item) => item.id} contentContainerStyle={styles.list} onEndReached={loadMore} onEndReachedThreshold={0.5} refreshControl={<RefreshControl refreshing={query.isRefetching && !query.isFetchingNextPage} onRefresh={() => void query.refetch()} tintColor={colors.primary} />} ListFooterComponent={query.isFetchingNextPage ? <ActivityIndicator color={colors.primary} style={styles.footer} /> : null} renderItem={({ item }) => <Link href={{ pathname: "/(app)/chat/[chatId]", params: { chatId: item.id } }} asChild><Pressable style={styles.card}><View style={styles.row}><Text style={styles.cardTitle}>{item.otherUser?.name || "Redrive member"}</Text>{item.unreadCount > 0 ? <Text style={styles.badge}>{item.unreadCount}</Text> : null}</View><Text numberOfLines={1} style={styles.meta}>{item.lastMessage?.text || (item.lastMessage?.imageUrl ? "Image" : "No messages yet")}</Text></Pressable></Link>} ListEmptyComponent={<Text style={styles.empty}>No conversations yet.</Text>} />}</SafeAreaView>;
}

const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.background }, header: { padding: spacing.lg, paddingBottom: spacing.sm, gap: spacing.xs }, title: { color: colors.ink, fontSize: 30, fontWeight: "800" }, detail: { color: colors.muted }, loader: { flex: 1 }, footer: { paddingVertical: spacing.md }, state: { padding: spacing.lg, gap: spacing.md }, list: { padding: spacing.lg, gap: spacing.sm }, card: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: radii.lg, padding: spacing.md, gap: spacing.sm }, row: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, cardTitle: { color: colors.ink, fontSize: 17, fontWeight: "800" }, badge: { color: "#FFFFFF", backgroundColor: colors.primary, borderRadius: 12, minWidth: 24, textAlign: "center", paddingVertical: 2, paddingHorizontal: 7, fontWeight: "800" }, meta: { color: colors.muted }, empty: { color: colors.muted, textAlign: "center", padding: spacing.xl } });
