import { useRouter } from "expo-router";
import { Pressable, StyleSheet, Text, View } from "react-native";

import { Heading, PrimaryButton } from "@/components/form-controls";
import { Screen } from "@/components/screen";
import { useSession } from "@/providers/session-provider";
import { colors, radii, spacing } from "@/theme/tokens";

export default function ProfileScreen() {
  const router = useRouter();
  const { user, logout, logoutAll } = useSession();
  return <Screen><Heading detail="Your identity, security, and mobile sessions.">Profile</Heading><View style={styles.card}><Text style={styles.name}>{user?.name || "Redrive member"}</Text><Text style={styles.detail}>{user?.email}</Text><Text style={styles.detail}>Email {user?.emailVerified ? "verified" : "not verified"}</Text><View style={styles.statusRow}><Text style={styles.statusLabel}>Licence</Text><Text style={styles.statusValue}>{user?.licenseStatus || "Not checked"}</Text></View></View><View style={styles.menu}><Pressable accessibilityRole="button" onPress={() => router.push("/(app)/profile/security")} style={({ pressed }) => [styles.menuItem, pressed && styles.pressed]}><View><Text style={styles.menuTitle}>Security and devices</Text><Text style={styles.menuCopy}>Login verification, password, and signed-in devices</Text></View><Text style={styles.chevron}>›</Text></Pressable><Pressable accessibilityRole="button" onPress={() => router.push("/(app)/profile/notifications")} style={({ pressed }) => [styles.menuItem, pressed && styles.pressed]}><View><Text style={styles.menuTitle}>Notifications</Text><Text style={styles.menuCopy}>Choose whether this device receives timely trip updates</Text></View><Text style={styles.chevron}>›</Text></Pressable><Pressable accessibilityRole="button" onPress={() => router.push("/(app)/profile/delete-account")} style={({ pressed }) => [styles.menuItem, styles.dangerItem, pressed && styles.pressed]}><View><Text style={[styles.menuTitle, styles.dangerText]}>Delete account</Text><Text style={styles.menuCopy}>Review consequences and permanently delete your data</Text></View><Text style={[styles.chevron, styles.dangerText]}>›</Text></Pressable></View><PrimaryButton title="Sign out of this device" tone="neutral" onPress={() => void logout()} /><PrimaryButton title="Sign out everywhere" tone="danger" onPress={() => void logoutAll()} /><Text style={styles.note}>Identity-document upload remains unavailable until the protected native upload slice passes its authorization and media-retention tests.</Text></Screen>;
}

const styles = StyleSheet.create({ card: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: radii.lg, padding: spacing.lg, gap: spacing.xs }, name: { color: colors.ink, fontSize: 20, fontWeight: "800" }, detail: { color: colors.muted }, statusRow: { marginTop: spacing.md, paddingTop: spacing.md, borderTopWidth: 1, borderTopColor: colors.border, flexDirection: "row", justifyContent: "space-between", gap: spacing.md }, statusLabel: { color: colors.muted }, statusValue: { color: colors.ink, fontWeight: "800" }, menu: { borderWidth: 1, borderColor: colors.border, borderRadius: radii.lg, overflow: "hidden", backgroundColor: colors.surface }, menuItem: { minHeight: 68, padding: spacing.md, flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: spacing.md, borderBottomWidth: 1, borderBottomColor: colors.border }, dangerItem: { borderBottomWidth: 0 }, menuTitle: { color: colors.ink, fontSize: 16, fontWeight: "800" }, menuCopy: { color: colors.muted, fontSize: 12, lineHeight: 18, marginTop: 2 }, chevron: { color: colors.primary, fontSize: 28 }, dangerText: { color: colors.danger }, pressed: { opacity: 0.7 }, note: { color: colors.muted, lineHeight: 20 } });
