import { NextResponse } from "next/server";
import prisma from "@/app/libs/prismadb";
import { getCurrentUserEnhanced } from "@/app/libs/auth-middleware";
import { writeAuditEvent } from "@/app/libs/security";

type Context = { params: Promise<{ reservationId: string }> };
async function participant(request: Request, id: string) { const user = await getCurrentUserEnhanced(request); if (!user) return null; const reservation = await prisma.reservation.findUnique({ where: { id }, select: { userId: true, listing: { select: { userId: true } } } }); return reservation && [reservation.userId, reservation.listing.userId].includes(user.id) ? user : null; }
export async function GET(request: Request, context: Context) { const { reservationId } = await context.params; if (!await participant(request, reservationId)) return NextResponse.json({ error: "Forbidden" }, { status: 403 }); return NextResponse.json(await prisma.incidentCase.findMany({ where: { reservationId }, orderBy: { createdAt: "desc" } })); }
export async function POST(request: Request, context: Context) { const { reservationId } = await context.params; const user = await participant(request, reservationId); if (!user) return NextResponse.json({ error: "Forbidden" }, { status: 403 }); const body = await request.json().catch(() => ({})); const summary = typeof body.summary === "string" ? body.summary.trim() : ""; if (summary.length < 10 || summary.length > 3000) return NextResponse.json({ error: "Describe what happened in 10 to 3000 characters" }, { status: 400 }); const incident = await prisma.incidentCase.create({ data: { reservationId, reporterUserId: user.id, type: typeof body.type === "string" ? body.type.slice(0, 50) : "OTHER", summary, location: typeof body.location === "string" ? body.location.slice(0, 300) : null, evidence: body.evidence || undefined } }); await writeAuditEvent({ request, actorUserId: user.id, action: "INCIDENT_REPORTED", targetType: "IncidentCase", targetId: incident.id, metadata: { reservationId } }); return NextResponse.json(incident, { status: 201 }); }
